// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADOm71X4shNY8KlvQhtCYSKwzdgB8avLo',
    appId: '1:775225688036:web:bb4f40c7cf6cf9eaa6d1f1',
    messagingSenderId: '775225688036',
    projectId: 'fir-bin-9ca76',
    authDomain: 'fir-bin-9ca76.firebaseapp.com',
    databaseURL: 'https://fir-bin-9ca76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bin-9ca76.appspot.com',
    measurementId: 'G-CM7JQKEGZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCu3AL6rq7Oao6pwev_C0VmJsUNbF0QhY',
    appId: '1:775225688036:android:276ccef6637cafa7a6d1f1',
    messagingSenderId: '775225688036',
    projectId: 'fir-bin-9ca76',
    databaseURL: 'https://fir-bin-9ca76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bin-9ca76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Q5KjH9tag6-W7CnHiYyI0c6WQaDBgW4',
    appId: '1:775225688036:ios:1fa243935ad23a43a6d1f1',
    messagingSenderId: '775225688036',
    projectId: 'fir-bin-9ca76',
    databaseURL: 'https://fir-bin-9ca76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bin-9ca76.appspot.com',
    androidClientId: '775225688036-k3c2k9075l269sljq9s2e6oc7chb1mim.apps.googleusercontent.com',
    iosClientId: '775225688036-k3ledo4jp9ivrt9hp4m7g5g85r5nocps.apps.googleusercontent.com',
    iosBundleId: 'com.example.sBinCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Q5KjH9tag6-W7CnHiYyI0c6WQaDBgW4',
    appId: '1:775225688036:ios:1fa243935ad23a43a6d1f1',
    messagingSenderId: '775225688036',
    projectId: 'fir-bin-9ca76',
    databaseURL: 'https://fir-bin-9ca76-default-rtdb.firebaseio.com',
    storageBucket: 'fir-bin-9ca76.appspot.com',
    androidClientId: '775225688036-k3c2k9075l269sljq9s2e6oc7chb1mim.apps.googleusercontent.com',
    iosClientId: '775225688036-k3ledo4jp9ivrt9hp4m7g5g85r5nocps.apps.googleusercontent.com',
    iosBundleId: 'com.example.sBinCollector',
  );
}
